export const DEFAULT_ABOUT_CONTENT = {
  subtitle: "à propos de ASM",
  title:
    "ASM-Une Société de Solutions Numériques pour la Transformation du Transport Multimodal en RDC",
  vision:
    "Aspirer à devenir un acteur de référence dans nos domaines d'activité, tant en République Démocratique du Congo qu'à l'international. Nous construisons cette ambition sur un socle d'expertise pointue, d'innovation continue et de valeurs humaines fortes.",
  mission:
    "Notre mission est d'inverser la tendance des pertes de revenus dues aux systèmes obsolètes. En exploitant la puissance du numérique, des données en temps réel et de processus transparents, nous accompagnons les institutions publiques pour optimiser la collecte, simplifier les procédures et libérer de nouvelles sources de revenus.",
  values: `<p><strong>Audace:</strong> Capacité de repousser ses limites, sortir de sa zone de confort pour réaliser des actions difficiles.</p>
<p><strong>Respect:</strong> Le strict respect aux règlements ainsi qu'à tous les membres du personnel et chacun des clients.</p>
<p><strong>Intégrité:</strong> Agir avec honnêteté, respect et prendre des décisions justes ainsi qu'être fidèle à nos valeurs.</p>
<p><strong>Loyauté:</strong> Respect de nos engagements par la fidélité à la parole donnée en interne aussi bien qu'en externe vis-à-vis de nos clients et partenaires.</p>`,
  paragraphs: [
    "African Shipping Management, en sigle ASM, est une société de solutions numériques et de gestion de données, spécialisée dans la transformation digitale des systèmes de collecte, de suivi et de sécurisation des redevances dans le secteur du transport multimodal en République Démocratique du Congo. Née d'un partenariat public-privé entre le Ministère des Transports, Voies de Communication et Désenclavement de la RDC et la société PADS Corporation, ASM accompagne l'État et ses partenaires dans la modernisation des procédures administratives, la mobilisation des recettes publiques et l'amélioration de la transparence dans les opérations liées au transport maritime, fluvial, lacustre, terrestre, ferroviaire et aérien.",
    "Notre mission est de mettre la technologie au service de la gouvernance publique. À travers des plateformes numériques modernes, sécurisées et accessibles, ASM contribue à remplacer les procédures manuelles par des processus digitalisés, traçables et plus efficaces. Notre approche vise à réduire les délais, limiter les erreurs, améliorer le contrôle, sécuriser les transactions et offrir aux autorités publiques des données fiables pour une meilleure prise de décision.",
    "ASM développe et déploie notamment SYGREM, le Système Intégré de Gestion des Redevances Multimodales. Cette solution permet de digitaliser les opérations de déclaration, de calcul, de contrôle, de paiement et de suivi des redevances liées aux activités du secteur des transports. Elle facilite la centralisation des données, la traçabilité des opérations, la production de rapports statistiques et l'optimisation des recettes publiques.",
    "Dans le cadre de ses solutions, ASM accompagne également l'OGEFREM dans la digitalisation et la gestion des redevances multimodales à travers SYGREM 2. Cette plateforme prend notamment en charge les opérations liées à la FERI, à l'Attestation de Destination de Continuité — ADC, à l'Attestation de Destination Régionale — ADR, à la FERE ainsi qu'à la Commission d'Intervention. Elle permet aux opérateurs économiques, aux services habilités et aux différents intervenants du secteur d'effectuer leurs démarches en ligne de manière simple, rapide, transparente et sécurisée.",
    "Au-delà du développement de plateformes, ASM propose une offre complète de services numériques adaptés au transport multimodal et à la logistique : plateformes de collecte numérique des redevances et taxes, tableaux de bord dynamiques, rapports en temps réel, optimisation des recettes, digitalisation des processus, automatisation des procédures, formation et renforcement des capacités des équipes publiques et privées.",
    "Notre vision est de devenir un acteur de référence dans la transformation numérique des systèmes de gestion des redevances en RDC et en Afrique. Nous croyons qu'une meilleure collecte des recettes ne se limite pas à une performance financière : elle renforce la confiance entre l'État, les entreprises et les citoyens, soutient le développement des infrastructures, améliore la qualité des services publics et consolide la gouvernance.",
    "Présente dans plusieurs villes de la RDC, notamment Kinshasa, Lubumbashi, Kolwezi, Kalemie, Kisangani, Matadi, Bukavu, Goma et Boma, ASM s'appuie sur des équipes engagées et proches des réalités locales. Cette implantation nationale nous permet de mieux comprendre les besoins du terrain, d'accompagner efficacement les institutions publiques et les opérateurs privés, et de proposer des solutions adaptées aux enjeux concrets du secteur.",
    "Nos valeurs reposent sur l'audace, l'intégrité, le respect et la loyauté. Elles guident notre manière de travailler, notre relation avec les institutions, notre engagement envers nos partenaires et notre volonté de bâtir des solutions durables, utiles et responsables.",
    "Chez ASM, nous ne construisons pas seulement des plateformes numériques. Nous bâtissons des outils de confiance, de transparence et de performance pour accompagner la modernisation du secteur des transports et contribuer au développement durable de la République Démocratique du Congo.",
  ],
};
